brandName: Rodi Digital
email: hello@rodi-digital.com
whatsapp: '+32499721771'
address: Stationsweg 19
postalCode: 5211 TV
city: '''s-Hertogenbosch'
btwNumber: NL867887370B01
linkedin: https://www.linkedin.com/company/rodi-digital
